projectname: myblog
username: zhengzhejun
author: 郑喆君
description: zhengzhejun blog
baseurl: 
gems:
- jekyll-sitemap
# markdown: redcarpet
markdown: kramdown 
redcarpet: 
    extensions: ["fenced_code_blocks", "tables"]
#   extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
safe: false
#pygments: true
highlighter: rouge
title: 郑喆君的博客
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
categories_path: category.html
tags_path: tag.html
